- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "Ansible"
    Trainer: "Lakshman"
    Duration: "120hrs"
  tasks:
  - name: print override information
    vars: # Task level variables
      Course: "DevOps"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from trainer {{Trainer}}, Duration is {{Duration}}."

  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from {{Trainer}}, Duration is {{Duration}}."