- name: default value
  hosts: localhost
  vars_files:
  - vars.yaml
  vars_prompt:
    - name: enter_username
      prompt: please enter username
      private: false
  tasks:
  - name: print default value
    
    ansible.builtin.debug:
      msg: 
      - "Hello {{course}}"
      - "print the username{{enter_username}}"