- name: default value
  hosts: localhost
  vars_files:
  - vars.yaml
  vars_prompt:
    - name: username
      prompt: please enter username
      private: false
  tasks:
  - name: print default value
    vars:
      desig: IT
    
    ansible.builtin.debug:
      msg: 
      - "Hello {{course}}"
      - "print the username{{username}}"
      - "desig 'is'{{desig}}"
      - "{{username| upper}}"
      - "{{username| lower}}"

- name: remove duplicate
  hosts: localhost
  vars:
    numbers: [1,1,2,3,4,4,4,2,4,5]
  tasks:
  - name: remove duplicate
    ansible.builtin.debug:
      msg: "{{numbers | unique }}"