- name: default value
  hosts: localhost
  vars_files:
  - vars.yaml
  vars_prompt:
    - name: username
      prompt: please enter username
      private: false
  tasks:
  - name: print default value
    vars:
      desig: IT
    
    ansible.builtin.debug:
      msg: 
      - "Hello {{course}}"
      - "print the username{{username}}"
      - "desig 'is'{{desig}}"
      - "{{username| upper}}"
      - "{{username| lower}}"