- name: default value
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks:
  - name: print default value
    vars_prompt:
    - name: enter-username
      prompt: please enter username
      private: false
    ansible.builtin.debug:
      msg: 
      - "Hello {{course}}"
      - "print the username{{enter-username}}"