- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{ items }}"
      state: latest
    loop:
    - mysql
    - nginx
    - postpix